services:
  consul:
    image: hashicorp/consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/udp
    labels:
      - "traefik.enable=true"
      - "traefik.consulcatalog.connect=true"
  traefik:
    image: traefik:v3.2
    depends_on:
      - consul
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.prefix=traefik"
      - "--providers.consulcatalog.endpoint.address=consul:8500"
      - "--serversTransport.insecureSkipVerify=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.developer_api.address=:8081"
      - "--log.level=DEBUG"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
