entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true

ping:
  entryPoint: "web"

providers:
  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    endpoint:
      address: "127.0.0.1:8500"
      scheme: "http"
  
