services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-etnrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db-data:
