apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-persistentclaim
  namespace: volume-persistentclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
